version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo "VITE_API_URL=$API_BASE_URL" > .env   # for Vite/React
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist
